//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musteri_Bakiye_Seyri_.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERİ_FATURA_TABLE
    {
        public int ID { get; set; }
        public Nullable<int> MUSTERİ_ID { get; set; }
        public Nullable<System.DateTime> FATURA_TARİHİ { get; set; }
        public int FATURA_TUTARI { get; set; }
        public System.DateTime ODEME_TARİHİ { get; set; }
    
        public virtual MUSTERİ_TANIM_TABLE MUSTERİ_TANIM_TABLE { get; set; }
    }
}
