//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musteri_Bakiye_Seyri_.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERİ_TANIM_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUSTERİ_TANIM_TABLE()
        {
            this.MUSTERİ_FATURA_TABLE = new HashSet<MUSTERİ_FATURA_TABLE>();
        }
    
        public int ID { get; set; }
        public string UNVAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUSTERİ_FATURA_TABLE> MUSTERİ_FATURA_TABLE { get; set; }
    }
}
